Use builder pattern for the configuration
meilisearch/arroy pull request #96
Opened 2024-09-25 12:36 UTC by irevoire

# Pull Request

## Related issue
Fixes https://github.com/meilisearch/arroy/issues/91

## What does this PR do?
- Provide a builder for querying the reader and building the trees

2024-09-25 18:03 UTC, Kerollmops requested changes
Could you also update the README to change
> with the interface of the [Annoy Python library](https://github.com/spotify/annoy/#full-python-api) to search for vectors in space that are close to a given query vector

By 

> with an interface close to the [Annoy Python library](https://github.com/spotify/annoy/#full-python-api) to search for vectors in space that are near a targeted vector

2024-09-25 18:03 UTC, Kerollmops commented on src/writer.rs
> +    /// [`rayon::ThreadPool::install`] to use it.
```suggestion
    /// [`rayon::ThreadPool::install`].
```

2024-09-26 08:09 UTC, irevoire commented on src/writer.rs
> +    /// After calling build, no more items can be added.
No, I removed it

2024-09-26 08:43 UTC, Kerollmops approved these changes
Thank you very much ❤️

2024-09-26 08:43 UTC, merged